version: "3.8"
services:
  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./apps/backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://crm-db:Clickcrm@crm-cluster-db.ykasl.mongodb.net/?retryWrites=true&w=majority&appName=crm-cluster-db
      